#
#Sun Nov 16 15:35:53 UTC 2025
acceptInsecureCerts=false
browserName=firefox
moz\:debuggerAddress=true
moz\:firefoxOptions={args\=[-headless], log\={level\=error}, prefs\={devtools.chrome.enabled\=false, devtools.debugger.remote-enabled\=true, remote.active-protocols\=1}}
webSocketUrl=true
