name: publish

on:
  workflow_dispatch:
    inputs:
      allure:
        description: 'The Allure version to publish'
        default: 'allure3'
        required: true
        type: choice
        options:
          - allure2
          - allure3

jobs:
  publish:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Modify homepage
        run: |
          ALLURE="${{ inputs.allure }}"
          if [ "$ALLURE" = "allure2" ]; then
            cp allure2.html docs/index.html
          else
            cp allure3.html docs/index.html
          fi

      - name: Commit changes
        run: |
          git config user.name "GitHub Actions"
          git config user.email "noreply@github.com"
          git add docs/index.html
          git commit -m "Update docs/index.html" || echo "No changes"
          git push
